#!/bin/bash

set -e

PROJECT_DIR="$1"

if [[ -z "$PROJECT_DIR" ]]; then
  echo "Usage: $0 <project_directory>"
  exit 1
fi

PROJECT_DIR=$(realpath "$PROJECT_DIR")

echo "🚀 Distributed Gradle Build - Master Setup"
echo "========================================="
echo ""
echo "This script sets up your master machine for DISTRIBUTED building"
echo "that utilizes CPU and memory from multiple worker machines."
echo ""

read -p "Enter worker IP addresses (space-separated): " -a WORKER_IPS
echo ""
echo "Setting up distributed build for workers: ${WORKER_IPS[*]}"
echo ""

# Install required packages
echo "📦 Installing required packages..."
sudo apt update
sudo apt install -y rsync openjdk-17-jdk jq curl

# Test SSH connectivity to all workers
echo "🔗 Testing SSH connectivity to workers..."
for ip in "${WORKER_IPS[@]}"; do
  if ! ssh -o BatchMode=yes -o ConnectTimeout=5 "$ip" echo "OK" >/dev/null 2>&1; then
    echo "❌ Error: Passwordless SSH to $ip failed."
    echo "💡 Setup passwordless SSH with: ssh-copy-id $ip"
    echo ""
    echo "Or run: ./setup_passwordless_ssh.sh"
    exit 1
  else
    echo "✅ SSH to $ip: OK"
  fi
done
echo ""

# Detect available CPU cores for distributed coordination
CORES=$(nproc --all)
MAX_WORKERS=$((CORES * 2))  # Overcommit safely

echo "🖥️  Master system resources:"
echo "   CPU Cores: $CORES"
echo "   Max parallel workers: $MAX_WORKERS"
echo ""

# Create configuration file
CONFIG_FILE="$PROJECT_DIR/.gradlebuild_env"
cat <<EOF > "$CONFIG_FILE"
# Distributed Gradle Build Configuration
# Generated by setup_master.sh on $(date)
export WORKER_IPS="${WORKER_IPS[*]}"
export MAX_WORKERS=$MAX_WORKERS
export PROJECT_DIR="$PROJECT_DIR"
export DISTRIBUTED_BUILD=true
export WORKER_TIMEOUT=300
export BUILD_CACHE_ENABLED=true
EOF

echo "⚙️  Configuration created: $CONFIG_FILE"
echo ""

# Create distributed build specific directories
mkdir -p "$PROJECT_DIR/.distributed/{logs,cache,metrics}"

echo "📁 Created distributed build directories:"
echo "   Logs: $PROJECT_DIR/.distributed/logs"
echo "   Cache: $PROJECT_DIR/.distributed/cache" 
echo "   Metrics: $PROJECT_DIR/.distributed/metrics"
echo ""

# Verify distributed build script exists
DISTRIBUTED_SCRIPT="$(dirname "$0")/distributed_gradle_build.sh"
if [[ -f "$DISTRIBUTED_SCRIPT" ]]; then
    echo "✅ Distributed build script found: distributed_gradle_build.sh"
else
    echo "❌ Error: distributed_gradle_build.sh not found"
    echo "   This is required for true distributed building."
    exit 1
fi

echo ""
echo "🎯 DISTRIBUTED BUILD SETUP COMPLETE"
echo "=================================="
echo ""
echo "Configuration Summary:"
echo "  Workers: ${#WORKER_IPS[@]} machines"
echo "  Project: $PROJECT_DIR"
echo "  Distributed build: ENABLED"
echo ""
echo "Usage:"
echo "  cd $PROJECT_DIR"
echo "  ./sync_and_build.sh [task]    # Now uses true distributed building"
echo "  ./distributed_gradle_build.sh [task]  # Direct distributed build"
echo ""
echo "Examples:"
echo "  ./sync_and_build.sh assemble   # Distributed assembly"
echo "  ./sync_and_build.sh test       # Distributed testing"
echo "  ./sync_and_build.sh clean      # Clean distributed artifacts"
echo ""
echo "The system now utilizes CPU and memory from all ${#WORKER_IPS[@]} workers!"
echo ""

# Optional: Setup build cache
if [[ "${SETUP_CACHE:-false}" == "true" ]]; then
    echo "🚀 Starting distributed build cache server..."
    echo "Run in background: cd $PROJECT_DIR && mkdir -p build-cache && python3 -m http.server 5000 --directory build-cache"
    echo "Then configure in gradle.properties:"
    echo "  org.gradle.caching=true"
    echo "  org.gradle.cache.http=${MASTER_IP}:5000"
fi
